[project]
authors = ["ecamo19 <erickcamo19@gmail.com>", "choat lab"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "HIE_lysimeters"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.5,<4"

