[project]
authors = ["ecamo19 <erickcamo19@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lysimeters_code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
