[project]
authors = ["ecamo19 <erickcamo19@gmail.com>", "Choat lab"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "choat_lysimeters"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[dependencies]
bash_kernel = ">=0.7.2,<0.10"
pip = ">=24.3.1,<25"
python = "==3.10.0"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.3,<5"
bash = ">=5.2.37,<6"
time = ">=1.9,<2"
ruff = ">=0.12.3,<0.13"

[pypi-dependencies]
phidget22 = "*"  
python-fasthtml = "*"
os-sys = "*"

[host-dependencies]
python = "==3.10.0"

[tasks]
balance_0 = { cmd = "python balance_0.py", cwd = "src"}
balance_1 = { cmd = "python balance_1.py", cwd = "src"}
balance_2 = { cmd = "python balance_2.py", cwd = "src"}
balance_3 = { cmd = "python balance_3.py", cwd = "src"}