[project]
authors = ["ecamo19 <erickcamo19@gmail.com>", "Choat lab"]
channels = ["conda-forge"]
description = "This project handles the code for getting weight measurements from the load cells bought from Phidget"
name = "choatlab_lysimeters"
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
bash_kernel = ">=0.7.2,<0.10"
pip = ">=24.3.1,<25"
python = "==3.10.0"
bash = ">=5.2.37,<6"
time = ">=1.9,<2"
ruff = ">=0.12.3,<0.13"

[pypi-dependencies]
phidget22 = "*"  
python-fasthtml = "*"
os-sys = "*"

[host-dependencies]
python = "==3.10.0"

[tasks]
balance = { cmd = "python main_balance.py", cwd = "src"}
