[project]
authors = ["ecamo19 <erickcamo19@gmail.com>", "Choat lab"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "choat_lysimeters"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[dependencies]
bash_kernel = ">=0.7.2,<0.10"
pip = ">=24.3.1,<25"
python = "==3.10.0"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.3,<5"
bash = ">=5.2.37,<6"

[pypi-dependencies]
phidget22 = "*"  
python-fasthtml = "*"

[host-dependencies]
python = "==3.10.0"

[tasks]
hello = { cmd = "echo hello"}
app =  { cmd = "python app.py", cwd = "src"}
test =  { cmd = "python test.py", cwd = "src"}